name: CI-CD Pipeline

permissions:
  contents: read
  packages: write
  id-token: write

on:
  push:
    paths:
      - 'src/Api/**'
      - 'src/Message/**'
  workflow_dispatch:

env:
  RESOURCE_GROUP: acmetickets-rg
  DOMAIN_SHORT_NAME: platformcomp
  APPCONFIG_NAME: AcmeTicketsInfraConfiguration

jobs:
  build-and-publish-api:
    uses: AcmeTickets/.github/.github/workflows/Build and Publish Docker Image.yml@main
    secrets: inherit
    with:
      project_path: src/Api/Api.csproj
      dockerfile_path: src/Api/Dockerfile
      image_name: ghcr.io/acmetickets/platformcomp-api
      target_port: 5001

  deploy-api:
    needs: build-and-publish-api
    runs-on: ubuntu-latest
    steps:
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Fetch App Config Values
        id: appconfig
        run: |
          az appconfig kv list --name "$APPCONFIG_NAME" --key "${DOMAIN_SHORT_NAME}:*" --query "[].{key:key, value:value}" -o tsv > config.txt
          while IFS=$'\t' read -r key value; do
            envname=$(echo $key | sed "s/^${DOMAIN_SHORT_NAME}://;s/__/_/g")
            echo "$envname=$value" >> $GITHUB_ENV
          done < config.txt

      - name: Deploy to Azure Container App
        env:
          IMAGE: ${{ needs.build-and-publish-api.outputs.image_tag }}
        run: |
          az containerapp update \
            --name platformcomp-api \
            --resource-group "$RESOURCE_GROUP" \
            --image "$IMAGE" \
            --set-env-vars AzureServiceBus__FullyQualifiedNamespace=$AzureServiceBus__FullyQualifiedNamespace COSMOSDB_ACCOUNT=$COSMOSDB_ACCOUNT CosmosDb__DatabaseName=$CosmosDb__DatabaseName CosmosDb__ContainerName=$CosmosDb__ContainerName CosmosDb__AccountEndpoint=$CosmosDb__AccountEndpoint

  build-and-publish-message:
    uses: AcmeTickets/.github/.github/workflows/Build and Publish Docker Image.yml@main
    secrets: inherit
    with:
      project_path: src/Message/Message.csproj
      dockerfile_path: src/Message/Dockerfile
      image_name: ghcr.io/acmetickets/platformcomp-msg

  deploy-message:
    needs: build-and-publish-message
    runs-on: ubuntu-latest
    steps:
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Fetch App Config Values
        id: appconfig
        run: |
          az appconfig kv list --name "$APPCONFIG_NAME" --key "${DOMAIN_SHORT_NAME}:*" --query "[].{key:key, value:value}" -o tsv > config.txt
          while IFS=$'\t' read -r key value; do
            envname=$(echo $key | sed "s/^${DOMAIN_SHORT_NAME}://;s/__/_/g")
            echo "$envname=$value" >> $GITHUB_ENV
          done < config.txt

      - name: Deploy to Azure Container App
        env:
          IMAGE: ${{ needs.build-and-publish-message.outputs.image_tag }}
        run: |
          az containerapp update \
            --name platformcomp-msg \
            --resource-group "$RESOURCE_GROUP" \
            --image "$IMAGE" \
            --set-env-vars AzureServiceBus__FullyQualifiedNamespace=$AzureServiceBus__FullyQualifiedNamespace COSMOSDB_ACCOUNT=$COSMOSDB_ACCOUNT CosmosDb__DatabaseName=$CosmosDb__DatabaseName CosmosDb__ContainerName=$CosmosDb__ContainerName CosmosDb__AccountEndpoint=$CosmosDb__AccountEndpoint